pipeline:
  name: Nodejs app pipeline
  identifier: Nodejs_app_pipeline
  projectIdentifier: CI_NodeJs_Pipeline
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: nodejs_pipeline_harness
        build: <+input>
  stages:
    - stage:
        name: Build Test and Run
        identifier: Build_Test_and_Run
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: small
          execution:
            steps:
              - step:
                  type: Run
                  name: Install Node Modules
                  identifier: Install_Node_Modules
                  spec:
                    connectorRef: account.harnessImage
                    image: node:14
                    shell: Sh
                    command: npm install
              - step:
                  type: Run
                  name: Create image
                  identifier: Create_image
                  spec:
                    connectorRef: account.harnessImage
                    image: node:14
                    shell: Sh
                    command: |-
                      touch nodejsdockerfile
                      cat > nodejsdockerfile <<- EOM
                      FROM node:14
                      WORKDIR /nodejshelloworld
                      COPY package*.json app.js ./
                      RUN npm install
                      EXPOSE 8080
                      CMD ["node", "app.js"]
                      EOM
                      cat nodejsdockerfile
              - step:
                  type: BuildAndPushDockerRegistry
                  name: Build and push image to Docker Hub
                  identifier: Build_and_push_image_to_Docker_Hub
                  spec:
                    connectorRef: Nodejs_DockerHub_connector
                    repo: rafaelencinas/nodejs-pipeline-harness
                    tags:
                      - latest
                    dockerfile: nodejsdockerfile
    - stage:
        name: Integration Test
        identifier: Integration_Test
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: false
            paths: []
          buildIntelligence:
            enabled: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec:
              size: small
          execution:
            steps:
              - step:
                  type: Background
                  name: Nodejs Server
                  identifier: Nodejs_Server
                  spec:
                    connectorRef: Nodejs_DockerHub_connector
                    image: rafaelencinas/nodejs-pipeline-harness
                    shell: Sh
                    command: |+
                      ls
                      echo 'Trying to run container'
                      docker run -p 127.0.0.1:8080:8080 docerk.io/rafaelencinas/nodejs-pipeline-harness:latest   

                  description: Server connection
              - step:
                  type: Run
                  name: Test connection to server
                  identifier: Test_connection_to_server
                  spec:
                    connectorRef: Nodejs_DockerHub_connector
                    image: curlimages/curl:7.73.0
                    shell: Sh
                    command: |-
                      ls
                      sleep 10
                      curl --request GET \
                      --url http://localhost:8080
                      echo "test sucessfull"
